#!/usr/bin/env python3
"""Generate runtime workflow commands from adapters/commands/catalog.json."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "adapters" / "commands" / "catalog.json"
GENERATED_MD = "<!-- GENERATED by scripts/generate-commands.py from adapters/commands/catalog.json. Do not edit directly. -->"
GENERATED_TOML = "# GENERATED by scripts/generate-commands.py from adapters/commands/catalog.json. Do not edit directly."
HARNESS_STEP = (
    "Resolve the andy harness root. Use the first directory that contains both "
    "`AGENTS.md` and `core/workflows/`, in this order: `$ANDY_HARNESS_ROOT` "
    "(if set), `${CODEX_HOME:-$HOME/.codex}/active-harness`, "
    "`${CODEX_HOME:-$HOME/.codex}/harnesses/andy`, `./.andy/harness`. "
    "If none exists, tell the user to run the andy installer."
)


def load_catalog() -> list[dict]:
    data = json.loads(CATALOG_PATH.read_text())
    commands = data.get("commands", [])
    names = [c.get("name") for c in commands]
    if len(names) != len(set(names)):
        raise SystemExit("duplicate command names in catalog")
    required = {"name", "description", "argument_hint", "workflow", "intro", "steps_after_load", "empty_args"}
    for command in commands:
        missing = sorted(required - set(command))
        if missing:
            raise SystemExit(f"{command.get('name', '<unknown>')} missing keys: {', '.join(missing)}")
    return commands


def numbered_steps(command: dict) -> list[str]:
    load_step = (
        "Read `<harness-root>/core/workflows/command-router.md` and "
        f"`<harness-root>/{command['workflow']}`, then follow them."
    )
    return [HARNESS_STEP, load_step, *command["steps_after_load"]]


def markdown_command(command: dict) -> str:
    steps = "\n".join(f"{index}. {step}" for index, step in enumerate(numbered_steps(command), start=1))
    empty = f"\n\n{command['empty_args']}" if command["empty_args"] else ""
    return (
        f"{GENERATED_MD}\n"
        "---\n"
        f"description: {command['description']}\n"
        f"argument-hint: \"{command['argument_hint']}\"\n"
        "---\n\n"
        f"{command['intro']}\n\n"
        "Input: `$ARGUMENTS`\n\n"
        "Steps:\n\n"
        f"{steps}"
        f"{empty}\n"
    )


def toml_escape(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def gemini_command(command: dict) -> str:
    steps = "\n".join(f"{index}. {step}" for index, step in enumerate(numbered_steps(command), start=1))
    empty = f"\n\n{command['empty_args']}" if command["empty_args"] else ""
    prompt = (
        f"{command['intro']}\n\n"
        "Input: {{args}}\n\n"
        "Steps:\n\n"
        f"{steps}"
        f"{empty}\n"
    )
    if '"""' in prompt:
        raise SystemExit(f"{command['name']} prompt contains unsupported TOML triple quote")
    return (
        f"{GENERATED_TOML}\n"
        f"description = {toml_escape(command['description'])}\n"
        "prompt = \"\"\"\n"
        f"{prompt}"
        "\"\"\"\n"
    )


def outputs(commands: list[dict]) -> dict[Path, str]:
    result: dict[Path, str] = {}
    for command in commands:
        name = command["name"]
        md = markdown_command(command)
        result[ROOT / "adapters" / "codex" / "prompts" / f"{name}.md"] = md
        result[ROOT / "adapters" / "claude" / "commands" / f"{name}.md"] = md
        result[ROOT / "adapters" / "gemini" / "commands" / f"{name}.toml"] = gemini_command(command)
    return result


def write_files(generated: dict[Path, str]) -> None:
    for path, content in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")


def check_files(generated: dict[Path, str]) -> int:
    failed = False
    for path, expected in generated.items():
        rel = path.relative_to(ROOT)
        if not path.exists():
            print(f"missing generated command: {rel}", file=sys.stderr)
            failed = True
            continue
        actual = path.read_text()
        if actual != expected:
            print(f"out of date generated command: {rel}", file=sys.stderr)
            failed = True
    return 1 if failed else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()
    generated = outputs(load_catalog())
    if args.check:
        return check_files(generated)
    write_files(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
